In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,])
arr

array([1, 2, 3, 4, 5, 6])

In [8]:
## Arithematic Operations withour inbuilt function

print(arr + 1)
print(arr - 1)
print(arr * 2)
print(arr / 2)
print(arr ** 2)


[2 3 4 5 6 7]
[0 1 2 3 4 5]
[ 2  4  6  8 10 12]
[0.5 1.  1.5 2.  2.5 3. ]
[ 1  4  9 16 25 36]


In [9]:
arr


array([1, 2, 3, 4, 5, 6])

In [10]:
arr = arr+1
arr

array([2, 3, 4, 5, 6, 7])

In [12]:
arr += 1
arr

array([4, 5, 6, 7, 8, 9])

In [14]:
arr *= 2
arr

array([16, 20, 24, 28, 32, 36])

In [15]:
## Max, Min 
arr.max()

36

In [16]:
arr.min()

16

In [17]:
arr.mean()

26.0

In [20]:
## With Multiple Array
arr = np.array([[1,2,3],
               [4,2,3],
               [5,6,7]])
arr

array([[1, 2, 3],
       [4, 2, 3],
       [5, 6, 7]])

In [23]:
## Column wise max value
arr.max(axis = 0)

array([5, 6, 7])

In [24]:
## Row wise max value
arr.max(axis = 1)

array([3, 4, 7])

In [25]:
## Column wise min value
arr.min(axis = 0)

array([1, 2, 3])

In [26]:
## Row wise max value
arr.min(axis = 1)

array([1, 2, 5])

In [27]:
## Total of Array
arr.sum()

33