In [1]:
import numpy as np

In [3]:
## Arithematic opearion on multiple column
arr1 = np.array([[1,2,3],
                [3,4,5],
                [5,6,7]])

arr2 = np.array([[3,4,3],
                [4,4,9],
                [8,6,7]])

In [5]:
arr1

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [6]:
arr2

array([[3, 4, 3],
       [4, 4, 9],
       [8, 6, 7]])

In [7]:
arr1 + arr2

array([[ 4,  6,  6],
       [ 7,  8, 14],
       [13, 12, 14]])

In [8]:
arr1 * arr2

array([[ 3,  8,  9],
       [12, 16, 45],
       [40, 36, 49]])

In [9]:
arr1

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [10]:
arr2

array([[3, 4, 3],
       [4, 4, 9],
       [8, 6, 7]])

In [12]:
## logic for dot method
(1*3) + (2*4) + (3*8)

35

In [11]:
## Dot Product multiplication
arr1.dot(arr2)

array([[ 35,  30,  42],
       [ 65,  58,  80],
       [ 95,  86, 118]])

In [13]:
arr2.dot(arr1)

array([[ 30,  40,  50],
       [ 61,  78,  95],
       [ 61,  82, 103]])

In [14]:
## INdexing
arr1

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [19]:
arr = np.array([1,2,3,4,5,6])
arr[3:-1]

array([4, 5])

In [20]:
arr1

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [21]:
arr1[:,:]

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [22]:
## Row Value
arr1[:,:1]

array([[1],
       [3],
       [5]])

In [25]:
## Column Value
arr1[:1 ,:]

array([[1, 2, 3]])

In [29]:
arr1[:,1:2]

array([[2],
       [4],
       [6]])

In [30]:
arr1[1:2,1:2]

array([[4]])

In [31]:
arr1[1:,1:]

array([[4, 5],
       [6, 7]])