In [1]:
import numpy as np

In [10]:
## Merging of Arrays
arr1 = np.array([[1,2,3,4], [5,6,7,8]])
arr2 = np.array([[3,4,5,6], [7,8,9,10]])

In [11]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
arr2

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [15]:
## Add Verically
np.vstack((arr1, arr2))
# np.vstack((arr2, arr1))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [18]:
## Add Horizontally
np.hstack((arr1, arr2))
# np.hstack((arr2, arr1))

array([[ 1,  2,  3,  4,  3,  4,  5,  6],
       [ 5,  6,  7,  8,  7,  8,  9, 10]])

In [21]:
## VErtically
arr = np.concatenate((arr1, arr1), axis = 0)

In [20]:
## Horizontally
np.concatenate((arr1, arr1), axis = 1)

array([[1, 2, 3, 4, 1, 2, 3, 4],
       [5, 6, 7, 8, 5, 6, 7, 8]])

In [22]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
## Spliting of Array Horizontally

np.hsplit(arr, 2)


[array([[1, 2],
        [5, 6],
        [1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8],
        [3, 4],
        [7, 8]])]

In [24]:
## Spliting of Array Vertically

np.vsplit(arr, 2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[1, 2, 3, 4],
        [5, 6, 7, 8]])]