In [1]:
import numpy as np

In [3]:
## Slicing Of Array
arr = np.array([[1,2,3,4],[5,6,7,8],[8,7,6,5],[4,3,2,1]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [4]:
arr[0][1]

2

In [5]:
arr[1][3]

8

In [6]:
arr[2][1]

7

In [7]:
arr[ : , :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [8]:
arr[ :1 , :]

array([[1, 2, 3, 4]])

In [9]:
arr[ 1: , :]

array([[5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [10]:
arr[ : , 1:]

array([[2, 3, 4],
       [6, 7, 8],
       [7, 6, 5],
       [3, 2, 1]])

In [11]:
arr[ : , :2]

array([[1, 2],
       [5, 6],
       [8, 7],
       [4, 3]])

In [12]:
arr[ : , 1:2]

array([[2],
       [6],
       [7],
       [3]])

In [13]:
arr[1,1]

6

In [14]:
arr[2,1]

7

In [15]:
arr[2,3]

5

In [16]:
arr[3,1]

3

In [17]:
## Crop Element
arr[ 1: , 1: ]

array([[6, 7, 8],
       [7, 6, 5],
       [3, 2, 1]])