In [1]:
import numpy as np


In [2]:
lst = [1,2,3,4,5,6,7,8,9,10]

In [9]:
## Without numpy
q = 0
for i in lst:
    if(i > 5):
        print(i)
        q += 1
print(q)


6
7
8
9
10
5


In [7]:
## With Numpy
lst = np.array([1,2,3,4,5,6,7,8,9,10])
lst

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
print(lst[lst > 5])
print(len(lst[lst > 5]))



[ 6  7  8  9 10]
5


In [15]:
print(lst[lst % 3 == 0])
print(len(lst[lst % 3 == 0]))


[3 6 9]
3


In [16]:
array1 = [1,2,3,5,4,6,7,8,5,3,2]
print(array1[2:-3])

[3, 5, 4, 6, 7, 8]


In [17]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b.T), axis=1)


array([[1, 2, 5],
       [3, 4, 6]])