In [1]:
import numpy as np


In [2]:
## Generating random number
np.random.random((3,3))

array([[0.98640446, 0.90252753, 0.70294606],
       [0.50957289, 0.46868947, 0.18749609],
       [0.26657052, 0.04936483, 0.08936352]])

In [6]:
## Generating sequence number
np.arange(1, 10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
## Linspace
np.linspace(1,11,10)

array([ 1.        ,  2.11111111,  3.22222222,  4.33333333,  5.44444444,
        6.55555556,  7.66666667,  8.77777778,  9.88888889, 11.        ])

In [16]:
# numpy.linspace method 
import numpy as geek
 
# restep set to True
print("B\n", geek.linspace(2.0, 3.0, num=5, retstep=True), "\n")
 
# To evaluate sin() in long range
x = geek.linspace(0, 2, 10)
print("A\n", geek.sin(x))


B
 (array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25) 

A
 [0.         0.22039774 0.42995636 0.6183698  0.77637192 0.8961922
 0.9719379  0.99988386 0.9786557  0.90929743]


In [11]:
## Before Reshaping
arr = np.random.random((4,3))
arr

array([[0.03122569, 0.28598693, 0.24423365],
       [0.65240864, 0.42419267, 0.93404489],
       [0.17254724, 0.54892554, 0.19744096],
       [0.67594494, 0.8001144 , 0.95407173]])

In [12]:
## Reshaping of Array
arr = np.reshape(arr, (3,4))
arr

array([[0.03122569, 0.28598693, 0.24423365, 0.65240864],
       [0.42419267, 0.93404489, 0.17254724, 0.54892554],
       [0.19744096, 0.67594494, 0.8001144 , 0.95407173]])

In [13]:
arr = np.reshape(arr, (6,2))
arr

array([[0.03122569, 0.28598693],
       [0.24423365, 0.65240864],
       [0.42419267, 0.93404489],
       [0.17254724, 0.54892554],
       [0.19744096, 0.67594494],
       [0.8001144 , 0.95407173]])

In [15]:
arr.flatten()

array([0.03122569, 0.28598693, 0.24423365, 0.65240864, 0.42419267,
       0.93404489, 0.17254724, 0.54892554, 0.19744096, 0.67594494,
       0.8001144 , 0.95407173])