In [1]:
import numpy as np

In [3]:
arr = np.array([[1,2,3,4,5,6],[5,6,7,8,4,4],[9,8,6,5,4,3]])
arr

array([[1, 2, 3, 4, 5, 6],
       [5, 6, 7, 8, 4, 4],
       [9, 8, 6, 5, 4, 3]])

In [4]:
## Sorting
## Row Wise
np.sort(arr, axis = 1, kind = 'mergesort')

array([[1, 2, 3, 4, 5, 6],
       [4, 4, 5, 6, 7, 8],
       [3, 4, 5, 6, 8, 9]])

In [6]:
## Column Wise
np.sort(arr, axis = 0, kind = 'mergesort')

array([[1, 2, 3, 4, 4, 3],
       [5, 6, 6, 5, 4, 4],
       [9, 8, 7, 8, 5, 6]])

In [7]:
np.sort(arr, axis = 1, kind = 'quicksort')

array([[1, 2, 3, 4, 5, 6],
       [4, 4, 5, 6, 7, 8],
       [3, 4, 5, 6, 8, 9]])