In [3]:
## Installing Numpy Library
# !pip install numpy
## Importing Numpy 
import numpy as np

In [13]:
lst = [[1,2,3,4],
       [5,6,7,8],
       [8,9,10,2]]

In [14]:
lst

[[1, 2, 3, 4], [5, 6, 7, 8], [8, 9, 10, 2]]

In [15]:
## Converting list to array
arr = np.array(lst)
print(arr)
print(type(arr))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 8  9 10  2]]
<class 'numpy.ndarray'>


In [16]:
## Checking Dimension of Array
arr.ndim

2

In [17]:
## Cheking Shape of Array
arr.shape

(3, 4)

In [19]:
## Checking Size of Array
arr.size

12

In [20]:
## Checking Type of Array
arr.dtype

dtype('int32')

In [22]:
## Creating Zero's Array
zeros = np.zeros((3,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
## Creating One's Array
ones = np.ones((4,3))
ones


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])